server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      ddl-auto: update
    show-sql: true
    database: postgresql
  kafka:
    template:
      default-topic: test-topic
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-group
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    url: jdbc:tc:postgresql:12:///postgres
    driverClassName: org.postgresql.Driver
    user: postgres
    password: postgres
    dropFirst: false
    default-schema: public
    liquibase-schema: public
    enabled: true


